version: '3'

networks:
  transcendence:
    name: transcendence

volumes:
  html:
    driver: local
    name: html
    driver_opts:
      type: none
      o: bind
      device: ./${FRONT_END_FOLDER}/html/

services:
  nginx:
    build:
      context: ${FRONT_END_FOLDER}/
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - html:/var/www/html
    networks:
      - transcendence
    restart: on-failure

  django:
    build:
      context: ${BACK_END_FOLDER}/
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - transcendence
    restart: on-failure