version: '3'

networks:
  transcendence:
    name: transcendence

volumes:
  html:
    driver: local
    name: html
    driver_opts:
      type: none
      o: bind
      device: ./${FRONT_END_FOLDER}/html/
  postgres_data:
    driver: local

services:
  nginx:
    build:
      context: ${FRONT_END_FOLDER}/
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - html:/var/www/html
    networks:
      - transcendence
    restart: on-failure

  django:
    build:
      context: ${BACK_END_FOLDER}/
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - transcendence
    restart: on-failure

  postgres:
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - transcendence
    restart: on-failure

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - transcendence