version: '3'

networks:
  transcendence:
    name: transcendence

volumes:
  html:
    driver: local
    name: html
    driver_opts:
      type: none
      o: bind
      device: ./FrontEnd/html/

services:
  nginx-html:
    build:
      context: FrontEnd/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - html:/var/www/html
    networks:
      - transcendence
    restart: on-failure