version: '3.8'

services:
  web:
    build:
      context: ./django
      dockerfile: Dockerfile-web
    command: uvicorn mainProject.asgi:application --host 0.0.0.0 --port 8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - static_volume:/home/app/web/staticfiles
    restart: on-failure
  
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres -h localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    ports:
      - 8000:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ssl_certificates:/etc/ssl
    restart: on-failure

  daphne:
    build:
      context: ./django/
      dockerfile: Dockerfile-daphne
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    depends_on:
      - web
    restart: on-failure
    volumes:
      - ssl_certificates:/etc/ssl

volumes:
  postgres_data:
  static_volume:
  ssl_certificates:
    driver: local
    name: ssl_certificates
    driver_opts:
      type: none
      o: bind
      device: ./ssl
